print('~~~'*20)
print('                 \033[4;35;40mCUPOM DE DESCONTO\033[m')
print('~~~'*20)
p=float(input('Valor do produto:'))
c=p*(1-0.05)
print('Valor R$ {:.2f} ao aplicar o cupom de 5% de desconto R$ {:.2f}'.format(p,c))