print('<->'*20)
print('                     \033[46mLeitura de nome\033[m')
print('<_>'*20)
nome=str(input('Digite seu nome completo:')).strip()
n=nome.split()
print('Muita satisfação em te conhecer!!!')
print('Seu primeiro nome é {}'.format(n[0]))
print('Seu ultimo nome é {}'.format(n[len(n)-1]))
